In [1]:
# Creating a date range
from datetime import datetime, timedelta

def generation_range(start_date, end_date):
    dates_list = []
    current_date = start_date
    
    while current_date <= end_date:
        dates_list.append(current_date.strftime('%Y-%m-%d'))
        current_date += timedelta(days=1)
    
    return dates_list

#string to date converter
def string_to_date_converter(date_string):
    parsed_date = datetime.strptime(date_string, "%Y-%m-%d")
    return parsed_date
# determine which date of the week it is
def getWeekDays(date): 
    unity = date.weekday()
    if (unity == 0):
        return 'Monday'
    elif (unity == 1):
        return 'Tuesday'
    elif (unity == 2):
        return 'Wednesday'
    elif (unity == 3):
        return 'Thursday'
    elif (unity == 4):
        return 'Friday'
    elif (unity == 5):
        return 'Saturday'
    elif (unity == 6):
        return 'Sunday'
    else:
        return 'No Method for this'
# determine if date is weekend
def is_weekend(date):
    return date.weekday() in (5, 6)

#determins if day is monthend
def is_month_end(input_date):
    next_day = input_date + timedelta(days=1)
    return input_date.month != next_day.month

In [2]:
#Create a function that does everything
import random

def generate_transaction(day):
    if_month_end_transact = {
        'Groceries': [2000, 1500, 1000, 2500],
        'Pay Bills' : [500, 40, 100, 900, 670, 458],
        'Miscellenous': [600, 480, 550]
    }

    if_party_transact = {
        'Transport': [10, 50, 60, 70, 100],
        'Party Present': [60, 70],
        'Party Miscel': [40, 50, 60, 70]
    }

    if_workday = {
        'Doughnut': 23,
        'Pizza': 45,
        'Fun fair': 34,
        'Bus': 20,
        'Coffee': 12,
        'Sweet': 5
    }

    if_weekend = {
        'Visitation': [20, 10, 5],
        'Treat': [30,40,20,10],
        'Development': [10,50, 40],
        'Gym': [10, 25, 28]
    }

    party_chooser = [True, False]

    weekday_transaction_total = [3, 4, 5]
    weekend_transaction_total = [2, 3]
    
    is_MonthEnd = 'NormalDay'
    what_Week_day = 'Workday'
    is_party = 'No'

    #get the week precise day
    dayname = getWeekDays(day)
    day_transaction = {}
    month_end_check = is_month_end(day)
    if (month_end_check):
        #print('It is Month end')
        is_MonthEnd = 'MonthEnd'
        monthys = if_month_end_transact
        #choosing the first element of if month
        main = next(iter(if_month_end_transact.keys()))
        main_value = random.choice(monthys[main]) #####
        day_transaction[main] = main_value
        del monthys[main]
        #choosing second random element
        random_mth_transact = random.choice(list(monthys.keys()))
        random_mth_transact_value = random.choice(monthys[random_mth_transact]) #####
        day_transaction[random_mth_transact] = random_mth_transact_value
        
    weekend_checker = is_weekend(day)
    if(weekend_checker):
        #print('It is weekend')
        what_Week_day = 'Weekend'
        is_there_party = random.choice(party_chooser)
        if(is_there_party):
            #print('There is party')
            is_party = 'Party'
            partying = if_party_transact
            for _ in range(len(partying)):
                chosen = random.choice(list(partying.keys()))
                chosen_value = random.choice(partying[chosen])#####
                day_transaction[chosen] = chosen_value
                del partying[chosen]
        else:
            #print('No party')
            set_transact = random.choice(weekend_transaction_total)
            weekend_transaction = random.sample((list(if_weekend.keys())), set_transact)
            for _ in range(set_transact):
                chosen = random.choice(weekend_transaction)
                chosen_value = random.choice(if_weekend[chosen])
                day_transaction[chosen] = chosen_value
                weekend_transaction.remove(chosen)
    else:
        #print('It is workday')
        set_transact = random.choice(weekday_transaction_total)
        workday_transaction = random.sample((list(if_workday.keys())), set_transact)
        for _ in range(set_transact):
            chosen = random.choice(workday_transaction)
            chosen_value = if_workday[chosen]
            day_transaction[chosen] = chosen_value
            workday_transaction.remove(chosen)
            
    return day_transaction, is_MonthEnd, what_Week_day, is_party, dayname

In [3]:
#creating the main function that generates and places all transactions
def genree(transaction, start_hour, end_hour, transaction_date, month_ending, week_days, is_party):
    magi = transaction
    linsting = []
    magi = list(magi.keys())
    name = 'Ibrahim'
    email = 'sulibrahim202@gmail.com'
    ipaddd = ['218.12.47.131', '26.51.167.24', '103.83.169.24','141.83.177.155', '179.78.175.197','44.154.58.200', '80.111.139.82','84.69.172.191','126.121.246.110','20.209.253.50','152.58.149.138']     
    counter = 1
    time_range = end_hour - start_hour
    interval = int(time_range / (len(magi) - 1))
    current_hour = start_hour

    for _ in range(len(magi)):
        random_minute = random.randint(0, 59)
        random_second = random.randint(0, 59)
        random_time = datetime.now().replace(hour=current_hour, minute=random_minute, second=random_second)
        dope = magi[-counter]
        
        #start the object creation
        transaction_time = random_time.strftime("%H:%M:%S")
        transaction_amount = transaction[dope]
        customer_name = name
        customer_email = email
        transaction_mode = random.choice(['Online Payment', 'Debit Card', 'Bank Transfer'])
        ip_address = random.choice(ipaddd)
        
        linsting.append({
            'Date': transaction_date,
            'Name': customer_name,
            'Email': customer_email,
            'Amount': transaction_amount,
            'Time': transaction_time,
            'IPAddress': ip_address,
            'TransactionMode': transaction_mode,
            'MonthEnd': month_ending,
            'WeekDay': week_days,
            'isParty': is_party,
            'isFraud': False,
        })
        
        current_hour += interval
        counter = counter + 1
    return linsting

In [4]:
# The main function that generates all transaction
def get_print_dates(start_date, end_date):
    all_transaction = []
    starter_date = string_to_date_converter(start_date)
    ending_date = string_to_date_converter(end_date)
    
    date_range = generation_range(starter_date, ending_date)
    for date in date_range:
        day = string_to_date_converter(date)
        transaf, monthend, weekday, party = generate_transaction(day)
        coded = genree(transaf, 7, 23, date, monthend, weekday, party)
        all_transaction.append(coded)
    
    return all_transaction

In [6]:
start_date = "2023-07-01"
end_date = "2023-07-07"

In [7]:
hue = get_print_dates(start_date, end_date)
hue

[[{'Date': '2023-07-01',
   'Name': 'Ibrahim',
   'Email': 'sulibrahim202@gmail.com',
   'Amount': 70,
   'Time': '07:39:38',
   'IPAddress': '179.78.175.197',
   'TransactionMode': 'Bank Transfer',
   'MonthEnd': 'NormalDay',
   'WeekDay': 'Weekend',
   'isParty': 'Party',
   'isFraud': False},
  {'Date': '2023-07-01',
   'Name': 'Ibrahim',
   'Email': 'sulibrahim202@gmail.com',
   'Amount': 50,
   'Time': '15:36:47',
   'IPAddress': '179.78.175.197',
   'TransactionMode': 'Bank Transfer',
   'MonthEnd': 'NormalDay',
   'WeekDay': 'Weekend',
   'isParty': 'Party',
   'isFraud': False},
  {'Date': '2023-07-01',
   'Name': 'Ibrahim',
   'Email': 'sulibrahim202@gmail.com',
   'Amount': 70,
   'Time': '23:28:31',
   'IPAddress': '84.69.172.191',
   'TransactionMode': 'Debit Card',
   'MonthEnd': 'NormalDay',
   'WeekDay': 'Weekend',
   'isParty': 'Party',
   'isFraud': False}],
 [{'Date': '2023-07-02',
   'Name': 'Ibrahim',
   'Email': 'sulibrahim202@gmail.com',
   'Amount': 40,
   'Time': '07:28:20',
   'IPAddress': '103.83.169.24',
   'TransactionMode': 'Bank Transfer',
   'MonthEnd': 'NormalDay',
   'WeekDay': 'Weekend',
   'isParty': 'No',
   'isFraud': False},
  {'Date': '2023-07-02',
   'Name': 'Ibrahim',
   'Email': 'sulibrahim202@gmail.com',
   'Amount': 20,
   'Time': '23:04:22',
   'IPAddress': '80.111.139.82',
   'TransactionMode': 'Debit Card',
   'MonthEnd': 'NormalDay',
   'WeekDay': 'Weekend',
   'isParty': 'No',
   'isFraud': False}],
 [{'Date': '2023-07-03',
   'Name': 'Ibrahim',
   'Email': 'sulibrahim202@gmail.com',
   'Amount': 12,
   'Time': '07:06:28',
   'IPAddress': '84.69.172.191',
   'TransactionMode': 'Bank Transfer',
   'MonthEnd': 'NormalDay',
   'WeekDay': 'Workday',
   'isParty': 'No',
   'isFraud': False},
  {'Date': '2023-07-03',
   'Name': 'Ibrahim',
   'Email': 'sulibrahim202@gmail.com',
   'Amount': 23,
   'Time': '12:46:10',
   'IPAddress': '141.83.177.155',
   'TransactionMode': 'Online Payment',
   'MonthEnd': 'NormalDay',
   'WeekDay': 'Workday',
   'isParty': 'No',
   'isFraud': False},
  {'Date': '2023-07-03',
   'Name': 'Ibrahim',
   'Email': 'sulibrahim202@gmail.com',
   'Amount': 45,
   'Time': '17:25:13',
   'IPAddress': '218.12.47.131',
   'TransactionMode': 'Bank Transfer',
   'MonthEnd': 'NormalDay',
   'WeekDay': 'Workday',
   'isParty': 'No',
   'isFraud': False},
  {'Date': '2023-07-03',
   'Name': 'Ibrahim',
   'Email': 'sulibrahim202@gmail.com',
   'Amount': 34,
   'Time': '22:51:21',
   'IPAddress': '152.58.149.138',
   'TransactionMode': 'Debit Card',
   'MonthEnd': 'NormalDay',
   'WeekDay': 'Workday',
   'isParty': 'No',
   'isFraud': False}],
 [{'Date': '2023-07-04',
   'Name': 'Ibrahim',
   'Email': 'sulibrahim202@gmail.com',
   'Amount': 20,
   'Time': '07:35:49',
   'IPAddress': '179.78.175.197',
   'TransactionMode': 'Debit Card',
   'MonthEnd': 'NormalDay',
   'WeekDay': 'Workday',
   'isParty': 'No',
   'isFraud': False},
  {'Date': '2023-07-04',
   'Name': 'Ibrahim',
   'Email': 'sulibrahim202@gmail.com',
   'Amount': 45,
   'Time': '11:52:10',
   'IPAddress': '141.83.177.155',
   'TransactionMode': 'Online Payment',
   'MonthEnd': 'NormalDay',
   'WeekDay': 'Workday',
   'isParty': 'No',
   'isFraud': False},
  {'Date': '2023-07-04',
   'Name': 'Ibrahim',
   'Email': 'sulibrahim202@gmail.com',
   'Amount': 23,
   'Time': '15:12:53',
   'IPAddress': '20.209.253.50',
   'TransactionMode': 'Debit Card',
   'MonthEnd': 'NormalDay',
   'WeekDay': 'Workday',
   'isParty': 'No',
   'isFraud': False},
  {'Date': '2023-07-04',
   'Name': 'Ibrahim',
   'Email': 'sulibrahim202@gmail.com',
   'Amount': 5,
   'Time': '19:52:02',
   'IPAddress': '179.78.175.197',
   'TransactionMode': 'Bank Transfer',
   'MonthEnd': 'NormalDay',
   'WeekDay': 'Workday',
   'isParty': 'No',
   'isFraud': False},
  {'Date': '2023-07-04',
   'Name': 'Ibrahim',
   'Email': 'sulibrahim202@gmail.com',
   'Amount': 34,
   'Time': '23:54:07',
   'IPAddress': '218.12.47.131',
   'TransactionMode': 'Debit Card',
   'MonthEnd': 'NormalDay',
   'WeekDay': 'Workday',
   'isParty': 'No',
   'isFraud': False}],
 [{'Date': '2023-07-05',
   'Name': 'Ibrahim',
   'Email': 'sulibrahim202@gmail.com',
   'Amount': 45,
   'Time': '07:58:27',
   'IPAddress': '179.78.175.197',
   'TransactionMode': 'Online Payment',
   'MonthEnd': 'NormalDay',
   'WeekDay': 'Workday',
   'isParty': 'No',
   'isFraud': False},
  {'Date': '2023-07-05',
   'Name': 'Ibrahim',
   'Email': 'sulibrahim202@gmail.com',
   'Amount': 12,
   'Time': '11:19:13',
   'IPAddress': '26.51.167.24',
   'TransactionMode': 'Online Payment',
   'MonthEnd': 'NormalDay',
   'WeekDay': 'Workday',
   'isParty': 'No',
   'isFraud': False},
  {'Date': '2023-07-05',
   'Name': 'Ibrahim',
   'Email': 'sulibrahim202@gmail.com',
   'Amount': 23,
   'Time': '15:52:09',
   'IPAddress': '80.111.139.82',
   'TransactionMode': 'Debit Card',
   'MonthEnd': 'NormalDay',
   'WeekDay': 'Workday',
   'isParty': 'No',
   'isFraud': False},
  {'Date': '2023-07-05',
   'Name': 'Ibrahim',
   'Email': 'sulibrahim202@gmail.com',
   'Amount': 5,
   'Time': '19:39:34',
   'IPAddress': '103.83.169.24',
   'TransactionMode': 'Online Payment',
   'MonthEnd': 'NormalDay',
   'WeekDay': 'Workday',
   'isParty': 'No',
   'isFraud': False},
  {'Date': '2023-07-05',
   'Name': 'Ibrahim',
   'Email': 'sulibrahim202@gmail.com',
   'Amount': 20,
   'Time': '23:39:10',
   'IPAddress': '84.69.172.191',
   'TransactionMode': 'Bank Transfer',
   'MonthEnd': 'NormalDay',
   'WeekDay': 'Workday',
   'isParty': 'No',
   'isFraud': False}],
 [{'Date': '2023-07-06',
   'Name': 'Ibrahim',
   'Email': 'sulibrahim202@gmail.com',
   'Amount': 5,
   'Time': '07:33:54',
   'IPAddress': '20.209.253.50',
   'TransactionMode': 'Debit Card',
   'MonthEnd': 'NormalDay',
   'WeekDay': 'Workday',
   'isParty': 'No',
   'isFraud': False},
  {'Date': '2023-07-06',
   'Name': 'Ibrahim',
   'Email': 'sulibrahim202@gmail.com',
   'Amount': 12,
   'Time': '11:33:58',
   'IPAddress': '126.121.246.110',
   'TransactionMode': 'Debit Card',
   'MonthEnd': 'NormalDay',
   'WeekDay': 'Workday',
   'isParty': 'No',
   'isFraud': False},
  {'Date': '2023-07-06',
   'Name': 'Ibrahim',
   'Email': 'sulibrahim202@gmail.com',
   'Amount': 20,
   'Time': '15:35:13',
   'IPAddress': '44.154.58.200',
   'TransactionMode': 'Debit Card',
   'MonthEnd': 'NormalDay',
   'WeekDay': 'Workday',
   'isParty': 'No',
   'isFraud': False},
  {'Date': '2023-07-06',
   'Name': 'Ibrahim',
   'Email': 'sulibrahim202@gmail.com',
   'Amount': 34,
   'Time': '19:54:38',
   'IPAddress': '26.51.167.24',
   'TransactionMode': 'Debit Card',
   'MonthEnd': 'NormalDay',
   'WeekDay': 'Workday',
   'isParty': 'No',
   'isFraud': False},
  {'Date': '2023-07-06',
   'Name': 'Ibrahim',
   'Email': 'sulibrahim202@gmail.com',
   'Amount': 45,
   'Time': '23:14:31',
   'IPAddress': '218.12.47.131',
   'TransactionMode': 'Online Payment',
   'MonthEnd': 'NormalDay',
   'WeekDay': 'Workday',
   'isParty': 'No',
   'isFraud': False}],
 [{'Date': '2023-07-07',
   'Name': 'Ibrahim',
   'Email': 'sulibrahim202@gmail.com',
   'Amount': 20,
   'Time': '07:06:57',
   'IPAddress': '84.69.172.191',
   'TransactionMode': 'Online Payment',
   'MonthEnd': 'NormalDay',
   'WeekDay': 'Workday',
   'isParty': 'No',
   'isFraud': False},
  {'Date': '2023-07-07',
   'Name': 'Ibrahim',
   'Email': 'sulibrahim202@gmail.com',
   'Amount': 45,
   'Time': '11:08:17',
   'IPAddress': '80.111.139.82',
   'TransactionMode': 'Online Payment',
   'MonthEnd': 'NormalDay',
   'WeekDay': 'Workday',
   'isParty': 'No',
   'isFraud': False},
  {'Date': '2023-07-07',
   'Name': 'Ibrahim',
   'Email': 'sulibrahim202@gmail.com',
   'Amount': 34,
   'Time': '15:49:43',
   'IPAddress': '103.83.169.24',
   'TransactionMode': 'Online Payment',
   'MonthEnd': 'NormalDay',
   'WeekDay': 'Workday',
   'isParty': 'No',
   'isFraud': False},
  {'Date': '2023-07-07',
   'Name': 'Ibrahim',
   'Email': 'sulibrahim202@gmail.com',
   'Amount': 5,
   'Time': '19:57:08',
   'IPAddress': '20.209.253.50',
   'TransactionMode': 'Bank Transfer',
   'MonthEnd': 'NormalDay',
   'WeekDay': 'Workday',
   'isParty': 'No',
   'isFraud': False},
  {'Date': '2023-07-07',
   'Name': 'Ibrahim',
   'Email': 'sulibrahim202@gmail.com',
   'Amount': 12,
   'Time': '23:28:49',
   'IPAddress': '141.83.177.155',
   'TransactionMode': 'Bank Transfer',
   'MonthEnd': 'NormalDay',
   'WeekDay': 'Workday',
   'isParty': 'No',
   'isFraud': False}]]

In [142]:
#huy = get_print_dates(start_date, end_date)
flattened_huy = [item for sublist in hue for item in sublist]

In [143]:
#Put everything in a dataFrame
import pandas as pd
df4 = pd.DataFrame(flattened_huy)
df4.head()

,Date,Name,Email,Amount,Time,IPAddress,TransactionMode,MonthEnd,WeekDay,isParty,isFraud
0,2023-03-01,Ibrahim,sulibrahim202@gmail.com,20,07:26:07,141.83.177.155,Online Payment,NormalDay,Workday,No,False
1,2023-03-01,Ibrahim,sulibrahim202@gmail.com,12,15:14:21,26.51.167.24,Online Payment,NormalDay,Workday,No,False
2,2023-03-01,Ibrahim,sulibrahim202@gmail.com,45,23:29:35,126.121.246.110,Online Payment,NormalDay,Workday,No,False
3,2023-03-02,Ibrahim,sulibrahim202@gmail.com,34,07:12:43,80.111.139.82,Debit Card,NormalDay,Workday,No,False
4,2023-03-02,Ibrahim,sulibrahim202@gmail.com,23,15:18:25,44.154.58.200,Bank Transfer,NormalDay,Workday,No,False

In [144]:
df4.to_csv('main2.csv')

In [9]:
import random
from datetime import datetime, timedelta

def generate_anomaly_transaction(start_hour, end_hour, total_transact):
    linsting = []
    counter = 1
    time_range = end_hour - start_hour
    interval = int(time_range / (total_transact - 1))
    current_hour = start_hour
    
    name = ['ibrahim', 'billy', 'migos', 'molly', 'seun', 'geotomz', 'master']
    email = ['yukinaxyz@wechat.com', 'billy4zone@recon.com', 'goebombarz@gmail.com', 'frigoglassmuti@xyz.app', 'muchiuchiha@yahoo.com']
    transaction_modes = ['dark web', 'online purchase', 'renewal', 'one time payment', 'unknown']
    isFraud = True
    ipadds = ['94.141.219.106', '151.228.41.182', '172.46.225.80', '120.91.63.242', '49.153.223.13', '83.29.94.120', '11.88.76.59']
    amount = [20000, 48900, 3000, 49, 50, 500, 290, 1000, 4400, 2990, 3900, 70, 90]
    
    for _ in range(total_transact):
        random_minute = random.randint(0, 59)
        random_second = random.randint(0, 59)
        random_time = datetime.now().replace(hour=current_hour, minute=random_minute, second=random_second)
        
        #start the object creation
        transaction_time = random_time.strftime("%H:%M:%S")
        transaction_amount = random.choice(amount)
        customer_name = random.choice(name)
        customer_email = random.choice(email)
        transaction_mode = random.choice(transaction_modes)
        ip_address = random.choice(ipadds)
        
        linsting.append({
            'Name': customer_name,
            'Email': customer_email,
            'Amount': transaction_amount,
            'Time': transaction_time,
            'IPAddress': ip_address,
            'TransactionMode': transaction_mode,
            'isFraud': isFraud,
        })
        
        current_hour += interval
        counter = counter + 1
    return linsting

In [10]:
def fardu(start, end, totally):
    maze = []
    for _ in range(totally):
        total =random.choice([2,3])
        kie = generate_anomaly_transaction(start, end, total)
        total =random.choice([2,3])
        maze.append(kie)
        
    return maze

In [11]:
start = 10
end = 23
total = 6

mild = fardu(start, end, total)
mild

[[{'Name': 'migos',
   'Email': 'yukinaxyz@wechat.com',
   'Amount': 500,
   'Time': '10:21:14',
   'IPAddress': '49.153.223.13',
   'TransactionMode': 'online purchase',
   'isFraud': True},
  {'Name': 'master',
   'Email': 'goebombarz@gmail.com',
   'Amount': 2990,
   'Time': '16:15:38',
   'IPAddress': '49.153.223.13',
   'TransactionMode': 'unknown',
   'isFraud': True},
  {'Name': 'molly',
   'Email': 'yukinaxyz@wechat.com',
   'Amount': 3000,
   'Time': '22:53:20',
   'IPAddress': '172.46.225.80',
   'TransactionMode': 'one time payment',
   'isFraud': True}],
 [{'Name': 'ibrahim',
   'Email': 'goebombarz@gmail.com',
   'Amount': 20000,
   'Time': '10:21:34',
   'IPAddress': '94.141.219.106',
   'TransactionMode': 'renewal',
   'isFraud': True},
  {'Name': 'master',
   'Email': 'frigoglassmuti@xyz.app',
   'Amount': 70,
   'Time': '23:59:05',
   'IPAddress': '120.91.63.242',
   'TransactionMode': 'renewal',
   'isFraud': True}],
 [{'Name': 'ibrahim',
   'Email': 'muchiuchiha@yahoo.com',
   'Amount': 70,
   'Time': '10:20:47',
   'IPAddress': '83.29.94.120',
   'TransactionMode': 'online purchase',
   'isFraud': True},
  {'Name': 'geotomz',
   'Email': 'billy4zone@recon.com',
   'Amount': 50,
   'Time': '16:11:00',
   'IPAddress': '94.141.219.106',
   'TransactionMode': 'dark web',
   'isFraud': True},
  {'Name': 'master',
   'Email': 'muchiuchiha@yahoo.com',
   'Amount': 49,
   'Time': '22:39:20',
   'IPAddress': '151.228.41.182',
   'TransactionMode': 'online purchase',
   'isFraud': True}],
 [{'Name': 'master',
   'Email': 'muchiuchiha@yahoo.com',
   'Amount': 290,
   'Time': '10:39:31',
   'IPAddress': '172.46.225.80',
   'TransactionMode': 'renewal',
   'isFraud': True},
  {'Name': 'master',
   'Email': 'yukinaxyz@wechat.com',
   'Amount': 2990,
   'Time': '16:28:49',
   'IPAddress': '151.228.41.182',
   'TransactionMode': 'one time payment',
   'isFraud': True},
  {'Name': 'geotomz',
   'Email': 'yukinaxyz@wechat.com',
   'Amount': 90,
   'Time': '22:59:57',
   'IPAddress': '49.153.223.13',
   'TransactionMode': 'online purchase',
   'isFraud': True}],
 [{'Name': 'ibrahim',
   'Email': 'muchiuchiha@yahoo.com',
   'Amount': 3900,
   'Time': '10:20:15',
   'IPAddress': '120.91.63.242',
   'TransactionMode': 'renewal',
   'isFraud': True},
  {'Name': 'seun',
   'Email': 'muchiuchiha@yahoo.com',
   'Amount': 1000,
   'Time': '16:53:07',
   'IPAddress': '83.29.94.120',
   'TransactionMode': 'unknown',
   'isFraud': True},
  {'Name': 'master',
   'Email': 'frigoglassmuti@xyz.app',
   'Amount': 1000,
   'Time': '22:44:22',
   'IPAddress': '83.29.94.120',
   'TransactionMode': 'unknown',
   'isFraud': True}],
 [{'Name': 'molly',
   'Email': 'billy4zone@recon.com',
   'Amount': 90,
   'Time': '10:52:01',
   'IPAddress': '94.141.219.106',
   'TransactionMode': 'one time payment',
   'isFraud': True},
  {'Name': 'master',
   'Email': 'billy4zone@recon.com',
   'Amount': 3000,
   'Time': '23:51:51',
   'IPAddress': '83.29.94.120',
   'TransactionMode': 'renewal',
   'isFraud': True}]]

In [47]:
flattened_anomaly = [item for sublist in mild for item in sublist]
df2 = pd.DataFrame(flattened_anomaly)
df2.head()

,Name,Email,Amount,Time,IPAddress,TransactionMode,isFraud
0,geotomz,yukinaxyz@wechat.com,50,09:17:38,151.228.41.182,online purchase,True
1,ibrahim,billy4zone@recon.com,20000,23:29:09,94.141.219.106,dark web,True
2,seun,billy4zone@recon.com,20000,09:01:09,94.141.219.106,one time payment,True
3,molly,goebombarz@gmail.com,3000,23:09:43,151.228.41.182,online purchase,True
4,billy,yukinaxyz@wechat.com,48900,09:32:17,11.88.76.59,dark web,True

In [48]:
df2.to_csv('anomaly.csv')

In [107]:
def replace_with_anomaly(normal_transact_df, anomaly_transact_df):
    normal_image_df = normal_transact_df
    rows = []
    anomaly_image_df = anomaly_transact_df
    for i in range(len(normal_transact_df)):
        rows.append(i)
        ++i
    fainty = random.sample(rows, len(anomaly_image_df))
    print(fainty)
    counter = 0
    
    for i in fainty:
        name = anomaly_image_df.loc[counter,'Name']
        email = anomaly_image_df.loc[counter,'Email']
        amt = anomaly_image_df.loc[counter,'Amount']
        time = anomaly_image_df.loc[counter,'Time']
        ip_add = anomaly_image_df.loc[counter,'IPAddress']
        transact_mode = anomaly_image_df.loc[counter,'TransactionMode']
        isFraud = anomaly_image_df.loc[counter,'isFraud']
        
        normal_image_df.loc[i, 'Name'] = name
        normal_image_df.loc[i,'Email'] = email
        normal_image_df.loc[i,'Amount'] = amt
        normal_image_df.loc[i,'Time'] = time
        normal_image_df.loc[i,'IPAddress'] = ip_add
        normal_image_df.loc[i,'TransactionMode'] = transact_mode
        normal_image_df.loc[i,'isFraud'] = isFraud
        
        counter = counter + 1
        
    return normal_transact_df

In [108]:
#data = pd.read_csv('data.csv')

In [145]:
df3 = replace_with_anomaly(df4, df2)

[195, 75, 154, 163, 181, 220, 79, 128, 192, 32, 70, 81, 96, 89, 164, 17, 51, 112, 153, 41, 171, 65, 84, 121, 52, 149, 127, 198, 183, 160, 201, 108, 88, 24, 13, 177, 80]

In [146]:
df3.iloc[75]

Date                         2023-03-23
Name                            ibrahim
Email              billy4zone@recon.com
Amount                            20000
Time                           23:29:09
IPAddress                94.141.219.106
TransactionMode                dark web
MonthEnd                      NormalDay
WeekDay                         Workday
isParty                              No
isFraud                            True
Name: 75, dtype: object

In [147]:
df3.to_csv('rematched2.csv')

### Start Creating the Anomaly Detection Model

In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import IsolationForest
from sklearn.metrics import classification_report

In [9]:
data = pd.read_csv('rematched2.csv')

In [10]:
data = data.drop(columns=['Unnamed: 0'])

In [11]:
data.head()

,Date,Name,Email,Amount,Time,IPAddress,TransactionMode,MonthEnd,WeekDay,isParty,isFraud
0,2023-03-01,Ibrahim,sulibrahim202@gmail.com,20,07:26:07,141.83.177.155,Online Payment,NormalDay,Workday,No,False
1,2023-03-01,Ibrahim,sulibrahim202@gmail.com,12,15:14:21,26.51.167.24,Online Payment,NormalDay,Workday,No,False
2,2023-03-01,Ibrahim,sulibrahim202@gmail.com,45,23:29:35,126.121.246.110,Online Payment,NormalDay,Workday,No,False
3,2023-03-02,Ibrahim,sulibrahim202@gmail.com,34,07:12:43,80.111.139.82,Debit Card,NormalDay,Workday,No,False
4,2023-03-02,Ibrahim,sulibrahim202@gmail.com,23,15:18:25,44.154.58.200,Bank Transfer,NormalDay,Workday,No,False

In [12]:
data['transaction_density'] = data.groupby('Date')['Amount'].transform('mean')

In [21]:
data.tail(3)

,Date,Name,Email,Amount,Time,IPAddress,TransactionMode,MonthEnd,WeekDay,isParty,isFraud,transaction_density
220,2023-05-01,ibrahim,goebombarz@gmail.com,90,23:00:09,151.228.41.182,dark web,NormalDay,Workday,No,True,35.8
221,2023-05-01,Ibrahim,sulibrahim202@gmail.com,20,19:50:00,20.209.253.50,Online Payment,NormalDay,Workday,No,False,35.8
222,2023-05-01,Ibrahim,sulibrahim202@gmail.com,34,23:10:13,179.78.175.197,Online Payment,NormalDay,Workday,No,False,35.8

In [16]:
# Converting all features to numerical value
data2 = data.drop(columns=['Time', 'MonthEnd', 'WeekDay', 'isParty', 'Date', 'isFraud' ])

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ['Name', 'Email', 'TransactionMode','IPAddress']
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                 one_hot,
                                 categorical_features)],
                               remainder='passthrough')

transformed_data = transformer.fit_transform(data2)
transformed_data

<223x42 sparse matrix of type '<class 'numpy.float64'>'
	with 1338 stored elements in Compressed Sparse Row format>

In [33]:
dat = data.drop(['isFraud'], axis=1)
one_hot_enc = OneHotEncoder()
category_encoded = one_hot_enc.fit_transform(dat[['Name', 'Email', 'IPAddress', 'TransactionMode']]).toarray()
encoded_df = pd.DataFrame(category_encoded, columns=one_hot_enc.get_feature_names_out(['Name', 'Email', 'IPAddress', 'TransactionMode']))
dat = pd.concat([dat, encoded_df], axis=1)
encoded_df.head()
#dat.head()

,Name_Ibrahim,Name_billy,Name_geotomz,Name_ibrahim,Name_master,Name_migos,Name_molly,Name_seun,Email_billy4zone@recon.com,Email_frigoglassmuti@xyz.app,...,IPAddress_84.69.172.191,IPAddress_94.141.219.106,TransactionMode_Bank Transfer,TransactionMode_Debit Card,TransactionMode_Online Payment,TransactionMode_dark web,TransactionMode_one time payment,TransactionMode_online purchase,TransactionMode_renewal,TransactionMode_unknown
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [46]:
train_data, test_data = train_test_split(encoded_df, test_size=0.2, random_state=42)
model = IsolationForest(contamination=0.05, random_state=42,)
anomaly_detector = model.fit(train_data)

C:\Users\user\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

In [24]:
train_data.head()

,Name_Ibrahim,Name_billy,Name_geotomz,Name_ibrahim,Name_master,Name_migos,Name_molly,Name_seun,Email_billy4zone@recon.com,Email_frigoglassmuti@xyz.app,...,IPAddress_84.69.172.191,IPAddress_94.141.219.106,TransactionMode_Bank Transfer,TransactionMode_Debit Card,TransactionMode_Online Payment,TransactionMode_dark web,TransactionMode_one time payment,TransactionMode_online purchase,TransactionMode_renewal,TransactionMode_unknown
127,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
66,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
73,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
96,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
119,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [47]:
anomaly_prediction = anomaly_detector.predict(test_data)
#anoly_df = pd.DataFrame(anomaly_prediction)
anoly_score = anomaly_detector.decision_function(test_data)
joiner = test_data
joiner['anomaly_analysis'] = anomaly_prediction
joiner['anomaly_score'] = anoly_score
joiner.head()

,Name_Ibrahim,Name_billy,Name_geotomz,Name_ibrahim,Name_master,Name_migos,Name_molly,Name_seun,Email_billy4zone@recon.com,Email_frigoglassmuti@xyz.app,...,TransactionMode_Bank Transfer,TransactionMode_Debit Card,TransactionMode_Online Payment,TransactionMode_dark web,TransactionMode_one time payment,TransactionMode_online purchase,TransactionMode_renewal,TransactionMode_unknown,anomaly_analysis,anomaly_score
9,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0.135581
84,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1,-0.025010
117,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0.143304
144,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0.137658
220,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-1,-0.019788

In [29]:
mint = data['isFraud']
mint.iloc[84]

True

In [30]:
#model.score_samples(test_data)

In [282]:
joiner.tail(50)

,Time_07:00:38,Time_07:01:25,Time_07:06:35,Time_07:07:00,Time_07:07:20,Time_07:07:25,Time_07:08:23,Time_07:08:52,Time_07:10:58,Time_07:11:51,...,TransactionMode_Online Payment,TransactionMode_dark web,TransactionMode_one time payment,TransactionMode_online purchase,TransactionMode_renewal,TransactionMode_unknown,isFraud_False,isFraud_True,anomaly_analysis,anomaly_score
131,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.023404
17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1,0.005203
166,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.040321
72,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.009552
194,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.024709
134,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.029796
184,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.033952
204,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.031021
63,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.022549
54,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.029519
107,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.030213
50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.029474
174,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.030209
219,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.016039
169,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.010595
58,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.024585
48,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.038211
88,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1,0.009245
21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.024396
57,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.023572
160,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1,0.018362
215,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.022384
187,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.024804
191,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.033695
129,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.031927
37,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.034234
157,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.028748
209,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.026528
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.039145
52,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1,0.000665
149,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1,0.013483
130,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.031730
151,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.032318
103,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.031855
99,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.043186
116,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.017538
87,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.043358
202,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.034682
74,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.033929
210,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.042719
121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1,0.004454
222,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.024238
20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.024384
188,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.028271
71,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.029030
106,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.023762
14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.034449
92,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.035652
179,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.026295
102,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0.035592

In [172]:
#train_data, test_data = train_test_split(data, test_size=0.2, random_state=42)
train_data, test_data = train_test_split(data, test_size=0.2, random_state=42)
#features = ['Amount', 'transaction_density', 'Time', 'Name', 'Email', 'IPAddress', 'TransactionMode']
model = IsolationForest(contamination=0.05, random_state=42)

In [204]:
data2.head()
#dft= pd.DataFrame(dane)
#dft.head()

,Name,Email,Amount,TransactionMode,isFraud,transaction_density
0,Ibrahim,sulibrahim202@gmail.com,20,Online Payment,False,25.666667
1,Ibrahim,sulibrahim202@gmail.com,12,Online Payment,False,25.666667
2,Ibrahim,sulibrahim202@gmail.com,45,Online Payment,False,25.666667
3,Ibrahim,sulibrahim202@gmail.com,34,Debit Card,False,34.000000
4,Ibrahim,sulibrahim202@gmail.com,23,Bank Transfer,False,34.000000

In [207]:
dummies = pd.get_dummies(data[['Name', 'Email', 'TransactionMode', 'isFraud']])
dummies.head()

,isFraud,Name_Ibrahim,Name_billy,Name_geotomz,Name_ibrahim,Name_master,Name_migos,Name_molly,Name_seun,Email_billy4zone@recon.com,...,Email_sulibrahim202@gmail.com,Email_yukinaxyz@wechat.com,TransactionMode_Bank Transfer,TransactionMode_Debit Card,TransactionMode_Online Payment,TransactionMode_dark web,TransactionMode_one time payment,TransactionMode_online purchase,TransactionMode_renewal,TransactionMode_unknown
0,False,1,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
1,False,1,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
2,False,1,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
3,False,1,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
4,False,1,0,0,0,0,0,0,0,0,...,1,0,1,0,0,0,0,0,0,0

In [173]:
#Refit model
Y = 
X_train, X_text, Y_train, Y_test = train_test_split(transformed_data,
                                                   y)

ValueError: could not convert string to float: '07:26:07'

In [36]:
X = data.drop(['isFraud'], axis=1)
Y = data['isFraud']

In [37]:
X

,Date,Name,Email,Amount,Time,IPAddress,TransactionMode,MonthEnd,WeekDay,isParty,transaction_density
0,2023-03-01,Ibrahim,sulibrahim202@gmail.com,20,07:26:07,141.83.177.155,Online Payment,NormalDay,Workday,No,25.666667
1,2023-03-01,Ibrahim,sulibrahim202@gmail.com,12,15:14:21,26.51.167.24,Online Payment,NormalDay,Workday,No,25.666667
2,2023-03-01,Ibrahim,sulibrahim202@gmail.com,45,23:29:35,126.121.246.110,Online Payment,NormalDay,Workday,No,25.666667
3,2023-03-02,Ibrahim,sulibrahim202@gmail.com,34,07:12:43,80.111.139.82,Debit Card,NormalDay,Workday,No,34.000000
4,2023-03-02,Ibrahim,sulibrahim202@gmail.com,23,15:18:25,44.154.58.200,Bank Transfer,NormalDay,Workday,No,34.000000
...,...,...,...,...,...,...,...,...,...,...,...
218,2023-05-01,Ibrahim,sulibrahim202@gmail.com,23,07:27:52,103.83.169.24,Online Payment,NormalDay,Workday,No,35.800000
219,2023-05-01,Ibrahim,sulibrahim202@gmail.com,12,11:03:41,179.78.175.197,Online Payment,NormalDay,Workday,No,35.800000
220,2023-05-01,ibrahim,goebombarz@gmail.com,90,23:00:09,151.228.41.182,dark web,NormalDay,Workday,No,35.800000
221,2023-05-01,Ibrahim,sulibrahim202@gmail.com,20,19:50:00,20.209.253.50,Online Payment,NormalDay,Workday,No,35.800000
222,2023-05-01,Ibrahim,sulibrahim202@gmail.com,34,23:10:13,179.78.175.197,Online Payment,NormalDay,Workday,No,35.800000

In [38]:
#Random Forest Classifier
rfc_encode = X.drop(['Time'], axis=1)
one_hot_enc = OneHotEncoder()
rfc_encoded = one_hot_enc.fit_transform(rfc_encode[['Name', 'Email', 'IPAddress', 'TransactionMode']]).toarray()
encoded_rfc_df = pd.DataFrame(rfc_encoded, columns=one_hot_enc.get_feature_names_out(['Name', 'Email', 'IPAddress', 'TransactionMode']))
encoded_rfc_df.head()

,Name_Ibrahim,Name_billy,Name_geotomz,Name_ibrahim,Name_master,Name_migos,Name_molly,Name_seun,Email_billy4zone@recon.com,Email_frigoglassmuti@xyz.app,...,IPAddress_84.69.172.191,IPAddress_94.141.219.106,TransactionMode_Bank Transfer,TransactionMode_Debit Card,TransactionMode_Online Payment,TransactionMode_dark web,TransactionMode_one time payment,TransactionMode_online purchase,TransactionMode_renewal,TransactionMode_unknown
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [42]:
#Random Forest Model
import numpy as np
from sklearn.ensemble import RandomForestRegressor
np.random.seed(42)

rfc = RandomForestRegressor()
X_train, X_text, Y_train, Y_test = train_test_split(rfc_encoded,
                                                   Y,
                                                   test_size=0.2)
mays = rfc.fit(X_train, Y_train)

In [43]:
mays.score(X_text, Y_test)

1.0

In [44]:
mays.predict(X_text)

array([0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.])

In [299]:
Y_test

9      False
84      True
117    False
144    False
220     True
113    False
68     False
104    False
177     True
185    False
55     False
15     False
198     True
25     False
30     False
45     False
171     True
82     False
207    False
97     False
93     False
18     False
79      True
141    False
147    False
143    False
196    False
67     False
60     False
101    False
211    False
69     False
16     False
189    False
156    False
114    False
159    False
111    False
75      True
180    False
140    False
205    False
183     True
120    False
165    False
Name: isFraud, dtype: bool

In [1]:
import pickle as plk

In [45]:
saved_isolation_model = 'anomaly_detection_model.pickle'

with open(saved_isolation_model, 'wb') as f:
    plk.dump(mays, f)

In [48]:
saved_regression_model = 'regressor_model.pickle'

with open(saved_regression_model, 'wb') as t:
    plk.dump(anomaly_detector,t)

In [49]:
# Reusing the saved Models
anomaly_forest = plk.load(open(saved_isolation_model, 'rb'))

In [52]:
tests = test_data.drop(['anomaly_analysis', 'anomaly_score'], axis=1)
anomaly_forest.predict(tests)

array([ 1, -1,  1,  1, -1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1])

In [53]:
regressor_reuse = plk.load(open(saved_regression_model, 'rb'))
regressor_reuse.predict(X_text)

array([0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.])